name: "[iOS] Unit Tests"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test (iOS)
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Swift
        uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: '6.0'

      - name: Install xcpretty
        run: gem install xcpretty
      
      - name: Install Dependencies
        run: xcodebuild -resolvePackageDependencies

      - name: Test
        run: xcodebuild test -scheme FaviconFinder -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' -skipPackagePluginValidation