name: "[macOS] Unit Tests"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test (macOS)
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Swift
        uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: '6.0'

      - name: Test
        run: swift test
