name: "[iOS] Unit Tests"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test (iOS)
    runs-on: macos-14
    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Setup Swift
        uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: '6.0'

      - name: Check Xcode Version
        run: xcodebuild -version

      - name: Install Dependencies
        run: xcodebuild -resolvePackageDependencies -verbose

      - name: Upload Xcode result bundle
        uses: actions/upload-artifact@v2
        with:
          name: xcresult
          path: "**/*.xcresult"

      # - name: Test
      #   run: xcodebuild test -scheme FaviconFinder -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' -skipPackagePluginValidation