name: SwiftLint - Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:5.5-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Run SwiftLint and annotate
      run: |
        # Run SwiftLint and capture output
        OUTPUT=$(swiftlint lint --reporter github-actions-logging)
        
        # Print the output so GitHub Actions can pick up annotations
        echo "$OUTPUT"
        
        # Fail the job if any violations are found
        if [ -n "$OUTPUT" ]; then
          echo "SwiftLint violations found. Failing the action."
          exit 1
        else
          echo "No SwiftLint violations found."
        fi