name: SwiftLint - Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:5.5-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Run SwiftLint and annotate
      run: |
        # Directly run SwiftLint without capturing output
        swiftlint lint --reporter github-actions-logging
        
        # Fail the job if any violations are found
      continue-on-error: true
      if: failure()
      run: |
        echo "SwiftLint violations found. Failing the action."
        exit 1